cabal-version:   3.0
name:            blog
version:         0.1.0.0
license:         BSD-3-Clause
license-file:    LICENSE
maintainer:      marktishuk@gmail.com
author:          Mark
synopsis:        A custom blog generator from markup files
description:
    This package provides a static blog generator
    from a custom markup format to HTML.
    It defines a parser for this custom markup format
    as well as an html pretty printer EDSL.

category:        Text
build-type:      Simple
extra-doc-files: CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/RoNiN-shadow/hBlog

library
    exposed-modules:
        Blog
        Blog.Convert
        Blog.Html
        Blog.Html.Internal
        Blog.Markup
        Blog.Directory
        Blog.Env

    hs-source-dirs:   src
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base ^>=4.18.0.0,
        directory >=1.3.8 && <1.4,
        filepath >=1.4.300 && <1.5,
        mtl >=2.3.1 && <2.4,
        time >=1.12.2 && <1.13

executable blog
    main-is:          Main.hs
    hs-source-dirs:   app
    other-modules:    OptParse
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base ^>=4.18.0.0,
        optparse-applicative >=0.19.0 && <0.20,
        directory,
        blog

test-suite blog-test
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    build-tool-depends: hspec-discover:hspec-discover
    hs-source-dirs:     test
    other-modules:
        MarkupParsingSpec
        SpecHook
        HtmlParsingSpec

    default-language:   Haskell2010
    ghc-options:        -threaded -rtsopts -with-rtsopts=-N
    build-depends:
        base ^>=4.18.0.0,
        blog,
        hspec,
        hspec-discover,
        raw-strings-qq
